name: Azure Deployment - Container App & Static Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: cultivate-ml-rg
  CONTAINER_APP_NAME: cultivate-ml-api
  ACR_NAME: cultivatemlregistry
  SWA_NAME: cultivate-ml-demos
  SWA_RG: cultivate-ml-prod

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name ${{ env.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          docker build -f Dockerfile.api-light -t ${{ env.ACR_NAME }}.azurecr.io/cultivate-ml-api:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/cultivate-ml-api:${{ github.sha }}

      - name: Update Container App
        run: |
          az containerapp update \
            --name ${{ env.CONTAINER_APP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --image ${{ env.ACR_NAME }}.azurecr.io/cultivate-ml-api:${{ github.sha }}

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "unified-demos"
          api_location: ""
          output_location: ""
          skip_app_build: true