name: Claude Code Review - Detailed

on:
  issue_comment:
    types: [created, edited]

jobs:
  claude-detailed-review:
    if: contains(github.event.comment.body, '@claude') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude Code Detailed Review
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: |
            A detailed code review has been requested for this PR.

            Please provide a comprehensive review covering:

            ### Architecture & Design
            - Does this follow established patterns in the codebase?
            - Is the solution appropriate for the problem?
            - Are there any scalability concerns?
            - Is the code maintainable?

            ### Code Quality
            - Are there any obvious bugs or edge cases?
            - Is error handling appropriate?
            - Is the code clear and readable?
            - Is there unnecessary complexity?

            ### Security
            - Are there any security vulnerabilities?
            - Are credentials/sensitive data handled correctly?
            - Is authentication/authorization proper?
            - Is input validation present?

            ### Testing
            - Is test coverage adequate?
            - Are edge cases covered?
            - Are tests meaningful?
            - Are there any test regressions?

            ### Performance
            - Are there any performance regressions?
            - Are database queries optimized (if applicable)?
            - Is frontend bundle size impact acceptable?
            - Are caching strategies considered?

            ### Documentation
            - Are changes properly documented?
            - Are commit messages clear?
            - Is API documentation updated (if applicable)?
            - Are comments explaining complex logic?

            Reference CLAUDE.md in the repository for coding standards.
            Be constructive and provide actionable feedback.
