name: Request Claude Review

on:
  issue_comment:
    types: [created, edited]

jobs:
  request-claude-review:
    if: contains(github.event.comment.body, '@claude') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Add Claude Review Request Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            const reviewRequest = `## 🤖 Claude Code Review Requested

            A detailed code review has been requested. Here's what to check:

            ### Architecture & Design
            - [ ] Follows established patterns
            - [ ] Solution is appropriate
            - [ ] No scalability concerns
            - [ ] Code is maintainable

            ### Code Quality
            - [ ] No obvious bugs
            - [ ] Error handling appropriate
            - [ ] Code is clear and readable
            - [ ] No unnecessary complexity

            ### Security
            - [ ] No vulnerabilities detected
            - [ ] Credentials handled correctly
            - [ ] Auth/authz proper
            - [ ] Input validation present

            ### Testing
            - [ ] Adequate coverage
            - [ ] Edge cases covered
            - [ ] Meaningful tests
            - [ ] No regressions

            ### Performance
            - [ ] No regressions
            - [ ] Queries optimized
            - [ ] Bundle size acceptable
            - [ ] Caching considered

            ### Documentation
            - [ ] Changes documented
            - [ ] Commit messages clear
            - [ ] API docs updated
            - [ ] Logic comments present

            Please refer to CLAUDE.md for coding standards.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: reviewRequest
            });

            // Add labels
            try {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['awaiting-review', 'claude-requested']
              });
            } catch (err) {
              console.log('Could not add labels');
            }
