# DEPRECATED: This workflow does NOT provide actual code reviews
# The official Claude Code GitHub App handles comprehensive reviews automatically
# This workflow only posted static templates and is no longer functional
#
# For actual Claude Code reviews:
# 1. Install the official Claude Code GitHub App on your repository
# 2. Configure it in repository settings with required permissions
# 3. The app will automatically review PRs on creation and @claude mentions
# 4. It provides actual code analysis, not just templates
#
# The Claude Code app performs real analysis of:
# - Architecture and Design patterns
# - Code Quality and best practices
# - Security vulnerabilities
# - Testing coverage and edge cases
# - Performance implications
# - Documentation completeness
#
# See: https://docs.claude.com/claude-code for proper integration

name: "[DEPRECATED] Claude Detailed Code Review"

on:
  schedule:
    # This workflow is disabled - run on a schedule that never triggers
    - cron: '0 0 31 2 *'  # Feb 31 - never happens

jobs:
  deprecated-notice:
    name: This workflow is deprecated
    runs-on: ubuntu-latest
    steps:
      - name: Notice
        run: |
          echo "This workflow is deprecated and does not provide real reviews"
          echo "The official Claude Code GitHub App should be used instead"
          echo "See documentation for proper integration setup"
