name: Detailed Code Review Request

on:
  issue_comment:
    types: [created, edited]

jobs:
  claude-detailed-review:
    if: contains(github.event.comment.body, '@claude') && github.event.issue.pull_request
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Post Detailed Review Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.issue.number;
            const detailedReview = `## 🔍 Detailed Code Review Requested

            Comprehensive review covering:

            ### Architecture & Design
            - [ ] Follows established patterns in codebase
            - [ ] Solution is appropriate for the problem
            - [ ] No scalability concerns
            - [ ] Code is maintainable

            ### Code Quality
            - [ ] No obvious bugs or edge cases
            - [ ] Error handling is appropriate
            - [ ] Code is clear and readable
            - [ ] No unnecessary complexity

            ### Security
            - [ ] No security vulnerabilities
            - [ ] Credentials/sensitive data handled correctly
            - [ ] Authentication/authorization proper
            - [ ] Input validation present

            ### Testing
            - [ ] Test coverage is adequate
            - [ ] Edge cases are covered
            - [ ] Tests are meaningful
            - [ ] No test regressions

            ### Performance
            - [ ] No performance regressions
            - [ ] Database queries optimized (if applicable)
            - [ ] Frontend bundle size impact acceptable
            - [ ] Caching strategies considered

            ### Documentation
            - [ ] Changes are properly documented
            - [ ] Commit messages are clear
            - [ ] API documentation updated (if applicable)
            - [ ] Comments explain complex logic

            **Reference:** CLAUDE.md for coding standards.`;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: detailedReview
            });

            // Add label for detailed review
            try {
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                labels: ['detailed-review-requested']
              });
            } catch (error) {
              console.log('Could not add label:', error.message);
            }
